version: "3"

services:
  service:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: service
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8000"
  db:
    image: postgresql:15
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: