version: "3.8"

services:
  service:
    build:
      context: backend/
      dockerfile: Dockerfile
    restart: always
    container_name: service
    depends_on:
      - db
    env_file:
      - backend/.env
    ports:
      - "8080:8000"
  db:
    image: postgres:15
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
